<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>com.kevin</groupId>
    <artifactId>demo-pom-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo-pom-parent</name>
    <packaging>pom</packaging>

    <properties>
        <spring-cloud.version>2025.1.1</spring-cloud.version>
        <demo.version>0.0.1-SNAPSHOT</demo.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Spring Cloud BOM -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.kevin</groupId>
                <artifactId>demo-microservice-common-starter</artifactId>
                <version>${demo.version}</version>
            </dependency>

            <dependency>
                <groupId>com.kevin</groupId>
                <artifactId>demo-client-starter</artifactId>
                <version>${demo.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
