# MSF Microservice Default Configuration
# This file is loaded automatically by msf-microservice-starter

# Server Configuration
server:
  shutdown: ${SERVER_SHUTDOWN:graceful}
spring:
  cloud:
    # Consul Service Discovery
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        health-check-interval: ${CONSUL_HC_INTERVAL:10s}
        instance-id: ${spring.application.name}_${spring.cloud.client.ip-address}_${server.port}
        service-name: ${SERVICE_NAME:${spring.application.name}}
        acl-token: ${CONSUL_TOKEN:}
        prefer-ip-address: ${CONSUL_PREFER_IP:true}
        query-passing: ${QUERY_PASSING:true}
        metadata:
          user-name: ${spring.security.user.name}
          user-password: ${spring.security.user.password}

    # Load Balancer
    loadbalancer:
      retry:
        enabled: ${LB_RETRY:true}
      cache:
        enabled: ${LB_CACHE:false}

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

# 剥离日志kafka配置，不占用默认spring.kafka配置
tracing:
  kafka:
    bootstrap-servers: ${TRACING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    template:
      defaultTopic: zipkin
