spring.cloud.consul.host=${CONSUL_HOST:localhost}
spring.cloud.consul.port=${CONSUL_PORT:8500}
spring.cloud.consul.discovery.acl-token=${CONSUL_TOKEN:5c72f559-9ef9-48b4-99c7-23e9092f9a0f}
spring.cloud.consul.discovery.service-name=${spring.application.name}
spring.cloud.consul.discovery.instance-id=${spring.application.name}_${spring.cloud.client.ip-address}_${server.port}
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.query-passing=true

management.endpoints.web.exposure.include=health,info,prometheus,metrics,circuitbreakers,ratelimiters,retries,bulkheads
management.endpoints.web.base-path=/actuator
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
