server:
  port: 9070

spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: demo-echo-service
              uri: lb://demo-echo-service
              predicates:
                - Path=/echo-producer/api/echo/**
              filters:
                - StripPrefix=1
            - id: demo-user-service
              uri: lb://demo-user-service
              predicates:
                - Path=/user-producer/api/users/**
              filters:
                - StripPrefix=1
            - id: demo-consumer-service
              uri: lb://demo-consumer-service
              predicates:
                - Path=/api/v1/consumer/**
              filters:
                - StripPrefix=3

logging:
  file:
    name: logs/${spring.application.name}.log
