server:
  port: 8090

spring:
  application:
    name: demo-micrometer-tracing
  cloud:
    # ==================== Consul 服务注册与发现 ====================
    consul:
      host: localhost
      port: 8500
      token: 5c72f559-9ef9-48b4-99c7-23e9092f9a0f
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}_${spring.cloud.client.ip-address}_${server.port}
        health-check-interval: 10s
        prefer-ip-address: true
        query-passing: true

# ==================== Resilience4j 熔断限流配置 ====================
resilience4j:
  circuitbreaker:
    # 熔断降级全局默认配置
    configs:
      default:
        # 熔断触发条件
        sliding-window-size: 100  # 基于最近100次请求计算失败率
        failure-rate-threshold: 50  # 失败率阈值：50%请求失败时熔断
        slow-call-rate-threshold: 80  # 慢调用阈值：80%请求为慢调用时熔断
        slow-call-duration-threshold: 2s  # 慢调用定义：超过2秒视为慢调用
        # 熔断持续时间
        wait-duration-in-open-state: 10s  # 熔断后等待10秒进入半开状态
        automatic-transition-from-open-to-half-open-enabled: true # 熔断器打开后，等待时间一到自动切换到HALF_OPEN，无需等待请求触发
        permitted-number-of-calls-in-half-open-state: 10  # 半开状态允许10个试探请求
        event-consumer-buffer-size: 10  # 存储熔断器状态变更事件的环形缓冲区大小
        register-health-indicator: true # 在/actuator/health端点显示熔断器健康状态

management:
  # ==================== Prometheus 指标配置 ====================
  endpoints:
    web:
      exposure:
        # 暴露 prometheus 端点，也可暴露所有端点: "*"
        include: health,info,prometheus,metrics
      base-path: /actuator  # 端点基础路径
  metrics:
    tags:
      application: ${spring.application.name}  # 为所有指标添加应用标签
    distribution:
      percentiles-histogram:
        http.server.requests: true  # 启用 HTTP 请求直方图
  # ==================== 链路追踪配置====================
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans

# ==================== Kafka 日志配置 ====================
logging:
  kafka:
    bootstrap-servers: localhost:9092
    topic: zipkin

# ==================== 内部服务 HttpExchange 配置 ====================
internal:
  api:
    base-url: http://localhost:8090

# ==================== WebClient 高并发配置 ====================
webclient:
  # 连接池配置（类似 feign.httpclient.max-connections-per-route）
  max-connections: 200              # 单服务最大连接数（Feign 默认 200）
  pending-acquire-max-count: 500    # 等待队列长度

  # 超时配置（完全对应 Feign 的 timeouts）
  connect-timeout: 2000               # 连接超时 2s（Feign 默认 10s）
  read-timeout: 5000                  # 读取超时 5s（Feign 默认 60s）
  write-timeout: 5000                 # 写入超时 5s（WebClient 特有）