server:
  port: 9070

spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: demo-echo-service
              uri: lb://demo-echo-service
              predicates:
                - Path=/api/v1/api/echo/**
              filters:
                - StripPrefix=2
            - id: demo-user-service
              uri: lb://demo-user-service
              predicates:
                - Path=/api/v1/api/users/**
              filters:
                - StripPrefix=2