spring.http.serviceclient.demo-echo-service.base-url=lb://demo-echo-service
spring.http.serviceclient.demo-user-service.base-url=lb://demo-user-service

# ==================== \u539F\u751F\u58F0\u660E\u5F0F HTTP \u5BA2\u6237\u7AEF\u914D\u7F6E ====================
spring.http.clients.connect-timeout=1s
spring.http.clients.read-timeout=2s

# ==================== Resilience4j\u7194\u65AD\u9650\u6D41\u914D\u7F6E ====================
resilience4j.circuitbreaker.configs.default.register-health-indicator=true
resilience4j.circuitbreaker.configs.default.sliding-window-size=3
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=1
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=true

resilience4j.timelimiter.configs.default.timeout-duration=10s
resilience4j.timelimiter.configs.default.cancel-running-future=true
