spring.http.serviceclient.demo-echo-service.base-url=lb://demo-echo-service
spring.http.serviceclient.demo-user-service.base-url=lb://demo-user-service

# ==================== Resilience4j?????? ====================
resilience4j.circuitbreaker.instances.demo-echo-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.demo-echo-service.sliding-window-size=3
resilience4j.circuitbreaker.instances.demo-echo-service.minimum-number-of-calls=1
resilience4j.circuitbreaker.instances.demo-echo-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.demo-echo-service.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.demo-echo-service.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.demo-echo-service.automatic-transition-from-open-to-half-open-enabled=true
