server:
  port: 8090

spring:
  application:
    name: demo-full
  cloud:
    # ==================== Consul 服务注册与发现 ====================
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        acl-token: ${CONSUL_TOKEN:5c72f559-9ef9-48b4-99c7-23e9092f9a0f}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}_${spring.cloud.client.ip-address}_${server.port}
        health-check-interval: 10s
        prefer-ip-address: true
        query-passing: true
    # ==================== 负载均衡配置 ====================
    loadbalancer:
      retry:
        enabled: true
      cache:
        enabled: false
  # ==================== 原生声明式 HTTP 客户端配置 ====================
  http:
    clients:
      # 全局：较宽松，给连接池留有余地
      connect-timeout: 1s
      read-timeout: 2s
    serviceclient:
      echo-client:
        base-url: "lb://demo-full"

management:
  # ==================== Prometheus 指标配置 ====================
  endpoints:
    web:
      exposure:
        # 暴露 prometheus 端点，也可暴露所有端点: "*"
        include: health,info,prometheus,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  # ==================== 链路追踪配置====================
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://${ZIPKIN_SERVER:localhost:9411}/api/v2/spans

# ==================== Kafka 日志配置 ====================
logging:
  kafka:
    bootstrap-servers: ${LOGGING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic: ${LOGGING_KAFKA_TOPIC:zipkin}

# ==================== Resilience4j熔断限流配置 ====================
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        register-health-indicator: true
#        sliding-window-size: 3
#        minimum-number-of-calls: 1
#        failure-rate-threshold: 50
#        wait-duration-in-open-state: 5s
#        permitted-number-of-calls-in-half-open-state: 1
#        automatic-transition-from-open-to-half-open-enabled: true
#  timelimiter:
#    configs:
#      default:
#        timeout-duration: 10s
#        cancel-running-future: true
